apiVersion: v1
kind: Service
metadata:
  name: node-express-service
spec:
  selector:
    app: node-express-app-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: clusterIP
